// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../node_modules/blockly/blocks_compressed.js', ['blockly_blocks_compressed'], [], {});
goog.addDependency('../../../../node_modules/blockly/generators/javascript.js', ['Blockly.JavaScript'], ['Blockly.Generator'], {});
goog.addDependency('../../../../node_modules/blockly/javascript_compressed.js', ['blockly_generators_compressed'], [], {});
goog.addDependency('../../../../node_modules/blockly/msg/js/en.js', ['Blockly.Msg.en'], ['Blockly.Msg'], {});
goog.addDependency('../../../../node_modules/bootstrap/dist/js/bootstrap.js', ['Bootstrap'], ['Jquery'], {});
goog.addDependency('../../../../node_modules/gsap/src/uncompressed/TweenMax.js', ['TimelineMax', 'TweenMax'], [], {});
goog.addDependency('../../../../node_modules/jquery/dist/jquery.js', ['Jquery'], [], {});
goog.addDependency('../../../../node_modules/pixi.js/dist/pixi.js', ['PIXI'], [], {});
goog.addDependency('../../../../src/js/Algorithms.js', ['Sorter.Algorithms'], ['Sorter'], {});
goog.addDependency('../../../../src/js/App.js', ['Sorter.App'], ['Blockly', 'Blockly.JavaScript', 'Blockly.Msg.en', 'PIXI', 'Sorter', 'Sorter.Blocks', 'Sorter.Controls', 'Sorter.Generators', 'Sorter.ToolBox', 'Sorter.VisualArray', 'goog.dom'], {});
goog.addDependency('../../../../src/js/Blocks.js', ['Sorter.Blocks'], ['Blockly', 'Blockly.Blocks', 'blockly_blocks_compressed'], {});
goog.addDependency('../../../../src/js/Controls.js', ['Sorter.Controls'], ['Bootstrap', 'Sorter'], {});
goog.addDependency('../../../../src/js/Generators.js', ['Sorter.Generators'], ['Blockly.JavaScript', 'blockly_generators_compressed'], {});
goog.addDependency('../../../../src/js/Sorter.js', ['Sorter'], [], {});
goog.addDependency('../../../../src/js/Start.js', ['Sorter.Start'], ['Sorter.App'], {});
goog.addDependency('../../../../src/js/ToolBox.js', ['Sorter.ToolBox'], ['Sorter', 'Sorter.Algorithms'], {});
goog.addDependency('../../../../src/js/VisualArray.js', ['Sorter.VisualArray'], ['PIXI', 'Sorter', 'TimelineMax', 'goog.events.EventTarget'], {});

/* input point */
goog.require('Sorter.Start');
